name: workflow.yml
on:
  push:
    branches:
      - main

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for accurate results of code analysis

      # Installs ReportGenerator and Stryker tools
      - name: Install required tools
        run: |
          dotnet tool install -g dotnet-stryker
          dotnet tool install -g dotnet-sonarscanner
          dotnet tool install -g coverlet.console
          
          
      - name: Start Static Code Analysis
        run: |
          dotnet sonarscanner begin \
          /k:"${{vars.PROJECT_KEY}}" \
          /d:sonar.host.url="${{vars.SONAR_URL}}" \
          /d:sonar.token="${{secrets.FITNESSTRACKERTOKEN}}" \
          /d:sonar.projectBaseDir="$(pwd)" \
          /d:sonar.cs.opencover.reportsPaths="$(pwd)/coverage/coverage.opencover.xml"\
          /d:sonar.qualitygate.wait=true \
          /d:sonar.qualitygate.timeout=300

      - name: Build
        run: dotnet build    
      
      # Executes unit tests while collecting code coverage
      - name: Run unit tests
        run: |
          mkdir -p coverage
          dotnet test \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=opencover \
            /p:CoverletOutput=$(pwd)/coverage/

      #Static code analysis
      - name: Complete Static Code Analysis
        run: |
          dotnet sonarscanner end \
          /d:sonar.token="${{secrets.FITNESSTRACKERTOKEN}}"  
      
      # Executes mutation tests using Stryker with a threshold of 60% mutation score
      - name: Run Mutation Tests
        working-directory: ./UnitTests
        run: dotnet stryker --project ./UnitTests.csproj --break-at 60 --output "stryker-report"

      # Uploads the Stryker report to the artifacts - make it run always even if previous steps fail
      - name: Collect Stryker Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: stryker-report
          path: stryker-report/reports/mutation-report.html
